### ISSUE TITLE
dotnet new dry run crashed..

### ISSUE THREAD

**Issue by gaheath** [jertje260/dotnet-new-extension#4]
Oopsie doopsie made a fucky wucky, please notify the code monkeys about this error at: github

{"error":{"killed":false,"code":2147500036,"signal":null,"cmd":"dotnet new nunit --dry-run --enable-pack true --framework netcoreapp3.1 --no-restore true --output d:\\Project\\PumpBerry\\Test "},"stdout":"\r\nAn update for template pack NUnit3.DotNetNew.Template::1.7.0 is available.\r\n install command: dotnet new -i NUnit3.DotNetNew.Template::1.7.1\r\n","stderr":"Creating this template will make changes to existing files:\r\n Overwrite UnitTest1.cs\r\n\r\nRerun the command and pass --force to accept and create.\r\n"}

**Comment by jertje260** [comment]
This might be a case I could handle, but if you read from the `stderr`:
```
Creating this template will make changes to existing files:
Overwrite UnitTest1.cs
Rerun the command and pass --force to accept and create.
```

Which means, since you are overriding the existing files, you will have to tick the force checkbox.

If I have time I will make an update to handle this specific case where it tells you to use force to make it work.
